// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ai_recruitment.Data;

#nullable disable

namespace ai_recruitment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813094052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ai_recruitment.Data.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ApplicantStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InterviewSched")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantStatusId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("ai_recruitment.Data.ApplicantStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("ApplicantStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate passed AI screening",
                            IsActive = true,
                            SortOrder = 1,
                            StatusName = "AI Screening passed"
                        },
                        new
                        {
                            StatusId = 2,
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is scheduled for an initial interview",
                            IsActive = true,
                            SortOrder = 2,
                            StatusName = "Initial Interview"
                        },
                        new
                        {
                            StatusId = 3,
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is scheduled for a technical interview",
                            IsActive = true,
                            SortOrder = 3,
                            StatusName = "Technical Interview"
                        },
                        new
                        {
                            StatusId = 4,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is scheduled for a final interview",
                            IsActive = true,
                            SortOrder = 4,
                            StatusName = "Final Interview"
                        },
                        new
                        {
                            StatusId = 5,
                            Color = "#06B6D4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is in the job offer stage",
                            IsActive = true,
                            SortOrder = 5,
                            StatusName = "Job Offer"
                        },
                        new
                        {
                            StatusId = 6,
                            Color = "#6366F1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is submitting required documents",
                            IsActive = true,
                            SortOrder = 6,
                            StatusName = "Requirements Gathering"
                        },
                        new
                        {
                            StatusId = 7,
                            Color = "#A855F7",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is undergoing background verification",
                            IsActive = true,
                            SortOrder = 7,
                            StatusName = "Background Check"
                        },
                        new
                        {
                            StatusId = 8,
                            Color = "#14B8A6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate is currently in the onboarding process",
                            IsActive = true,
                            SortOrder = 8,
                            StatusName = "Onboarding"
                        },
                        new
                        {
                            StatusId = 9,
                            Color = "#22C55E",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Job offer has been formally extended to the candidate",
                            IsActive = true,
                            SortOrder = 9,
                            StatusName = "Offered"
                        },
                        new
                        {
                            StatusId = 10,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Candidate was rejected during the recruitment process",
                            IsActive = true,
                            SortOrder = 10,
                            StatusName = "Rejected"
                        });
                });

            modelBuilder.Entity("ai_recruitment.Data.Applicant", b =>
                {
                    b.HasOne("ai_recruitment.Data.ApplicantStatus", "ApplicantStatus")
                        .WithMany("Applicants")
                        .HasForeignKey("ApplicantStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantStatus");
                });

            modelBuilder.Entity("ai_recruitment.Data.ApplicantStatus", b =>
                {
                    b.Navigation("Applicants");
                });
#pragma warning restore 612, 618
        }
    }
}
